// tailwind-platfrom-app-react/src/components/DataGrid.js
import React, { useState, useEffect } from "react";
import Axios from "axios";
import DataTable from "react-data-table-component";
import { Link, useNavigate } from "react-router-dom";
import BootyPagination from "./BootyPagination";

const DataGrid = () => {
  const [data, setData] = useState([]);
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [sortCriteria, setSortCriteria] = useState("platformName");
  const [filter, setFilter] = useState("");

  useEffect(() => {
    fetchData();
  }, []);

  useEffect(() => {
    localStorage.setItem("sortCriteria", sortCriteria);
  }, [sortCriteria]);

  const navigate = useNavigate();

  const fetchData = async () => {
    try {
      const response = await Axios.get("http://localhost:3004/platforms");
      const sortedData = sortData(response.data, sortCriteria);
      setData(sortedData);
    } catch (error) {
      console.error("Error fetching data:", error);
    }
  };

  const startIndex = (currentPage - 1) * pageSize;
  const endIndex = startIndex + pageSize;

  const handleSort = (criteria) => {
    const sortedData = sortData(data, criteria);
    setData(sortedData);
    setSortCriteria(criteria);
  };

  const handlePageChange = (page) => {
    setCurrentPage(page);
  };

  const handlePerPageChange = (newPageSize) => {
    setPageSize(newPageSize);
    setCurrentPage(1);
  };

  const sortData = (data, criteria) => {
    return [...data].sort((a, b) => {
      if (criteria === "platformName") {
        return a.platformName.localeCompare(b.platformName);
      } else if (criteria === "inventoryDate") {
        return new Date(a[criteria]) - new Date(b[criteria]);
      } else if (criteria === "id" || criteria === "length") {
        return a[criteria] - b[criteria];
      }
    });
  };

  const handleFilterChange = (e) => {
    setFilter(e.target.value);
  };

  const handleClearFilter = () => {
    setFilter(""); // Clear the filter by setting it to an empty string
  };

  const filteredData = data.filter((row) => {
    return Object.values(row).some((value) => {
      if (typeof value === "string") {
        return value.toLowerCase().includes(filter.toLowerCase());
      } else if (typeof value === "number") {
        return value === Number(filter); // Exact match for numbers
      } else if (value instanceof Date) {
        const formattedDate = value.toISOString().substring(0, 10);
        return formattedDate.includes(filter);
      }
      return false;
    });
  });

  const columns = [
    {
      name: "Platform Name",
      selector: (row) => row.platformName,
      sortable: true,
    },
    {
      name: "ID",
      selector: (row) => row.id,
      sortable: true,
    },
    {
      name: "Inventory Date",
      selector: (row) => row.inventoryDate,
      sortable: true,
    },
    {
      name: "Length",
      selector: (row) => row.length,
      sortable: true,
    },
    {
      name: "Width",
      selector: (row) => row.width,
      sortable: true,
    },
    {
      name: "Height",
      selector: (row) => row.height,
      sortable: true,
    },
    {
      name: "Max Speed",
      selector: (row) => row.maxSpeed,
      sortable: true,
    },
    {
      name: "Min Speed",
      selector: (row) => row.minSpeed,
      sortable: true,
    },
    {
      name: "Actions",
      cell: (row) => (
        <div class="flex space-x-2">
          <Link
            to={`/item/${row.id}`}
            class="text-blue-700 hover:text-gray-800"
          >
            View
          </Link>
          <Link
            to={`/item/${row.id}/edit`}
            class="text-gray-700 hover:text-gray-800"
          >
            Edit
          </Link>
          <button onClick={() => {}} class="text-red-500 hover:text-red-600">
            Delete
          </button>
        </div>
      ),
    },
  ];

  return (
    <div className="bg-white p-4 shadow-md rounded-lg">
      <div className="mb-4 flex items-center justify-evenly">
        <div>
          <label className="mr-2">Filter by:</label>
          <input
            type="text"
            value={filter}
            onChange={handleFilterChange}
            className="border border-gray-300 p-1 rounded-md mr-2"
          />
          <button
            onClick={handleClearFilter}
            className="px-2 py-1 rounded-md bg-red-500 text-white hover:bg-red-600"
          >
            Clear
          </button>
        </div>
        <div>
          <label className="mr-2">Rows per page:</label>
          <select
            value={pageSize}
            onChange={(e) => handlePerPageChange(Number(e.target.value))}
            className="border border-gray-300 p-1 rounded-md"
          >
            <option value={10}>10</option>
            <option value={20}>20</option>
            <option value={150}>A Lot</option>
          </select>
        </div>
      </div>

      <DataTable
        columns={columns}
        data={filteredData.slice(startIndex, endIndex)}
        pagination
        paginationComponent={(props) => (
          <BootyPagination
            {...props}
            totalItems={data.length}
            itemsPerPage={pageSize}
            currentPage={currentPage}
            onPageChange={handlePageChange}
          />
        )}
      />
    </div>
  );
};

export default DataGrid;

// tailwind-platform-app-vue/src/components/DataGrid.vue
<template>
  <div class="bg-gray-200 p-4 shadow-md rounded-lg">
    <b-container fluid>
      <!-- User Interface controls -->
      <b-row class="mb-4 justify-evenly">
        <b-col lg="6" class="my-1">
          <b-form-group
            label="Filter"
            label-for="filter-input"
            label-cols-sm="3"
            label-align-sm="right"
            label-size="sm"
            class="mb-0"
          >
            <b-input-group size="sm">
              <b-form-input
                id="filter-input"
                v-model="filter"
                type="search"
                placeholder="Type to Search"
              ></b-form-input>

              <b-input-group-append>
                <b-button :disabled="!filter" @click="clearFilter" class="bg-red-700">Clear</b-button>
              </b-input-group-append>
            </b-input-group>
          </b-form-group>
        </b-col>

        <b-col lg="6" class="my-1">
          <b-form-group
            label="Per page"
            label-for="per-page-select"
            label-cols-sm="6"
            label-cols-md="4"
            label-cols-lg="3"
            label-align-sm="right"
            label-size="sm"
            class="mb-0"
          >
            <b-form-select
              id="per-page-select"
              v-model="perPage"
              :options="pageOptions"
              size="sm"
            ></b-form-select>
          </b-form-group>
        </b-col>
      </b-row>

      <!-- Main table element -->
      <b-table
        :items="sortedAndFilteredData"
        :fields="fields"
        :current-page="currentPage"
        :per-page="perPage"
        :filter="filter"
        :filter-included-fields="filterOn"
        :sort-by.sync="sortBy"
        :sort-desc.sync="sortDesc"
        class="bg-white p-4 shadow-md rounded-lg"
        stacked="md"
        show-empty
        small
        @filtered="onFiltered"
      >
        <!-- Customize the columns as needed -->
        <template #cell(platformName)="row">
          {{ row.item.platformName }}
        </template>
        <template #cell(id)="row">
          {{ row.item.id }}
        </template>
        <template #cell(inventoryDate)="row">
          {{ row.item.inventoryDate }}
        </template>
        <template #cell(length)="row">
          {{ row.item.length }}
        </template>
        <template #cell(width)="row">
          {{ row.item.width }}
        </template>
        <template #cell(height)="row">
          {{ row.item.height }}
        </template>
        <template #cell(maxSpeed)="row">
          {{ row.item.maxSpeed }}
        </template>
        <template #cell(minSpeed)="row">
          {{ row.item.minSpeed }}
        </template>
        <template #cell(actions)="row">
          <!-- Replace the action buttons with spaced-out links -->
          <b-link :to="`/view/${row.item.id}`" class="text-blue-500 hover:text-blue-700  mr-2">View</b-link>
          <b-link :to="`/edit/${row.item.id}`" class="text-black hover:text-gray-700  mr-2">Edit</b-link>
          <b-link @click="confirmDelete(row.item)" class="text-red-500 hover:text-red-700 ">Delete</b-link>
        </template>
      </b-table>

      <b-pagination
        v-model="currentPage"
        :total-rows="totalRows"
        :per-page="perPage"
        align="center"
        size="sm"
        class="my-0"
      ></b-pagination>
    </b-container>
  </div>
</template>

<script>
import axios from 'axios'

export default {
  data() {
    return {
      data: [], // Store your data here
      fields: [
        { key: 'platformName', label: 'Platform Name', sortable: true },
        { key: 'id', label: 'ID', sortable: true },
        { key: 'inventoryDate', label: 'Inventory Date', sortable: true },
        { key: 'length', label: 'Length', sortable: true },
        { key: 'width', label: 'Width', sortable: true },
        { key: 'height', label: 'Height', sortable: true },
        { key: 'maxSpeed', label: 'Max Speed', sortable: true },
        { key: 'minSpeed', label: 'Min Speed', sortable: true },
        { key: 'actions', label: 'Actions' } // Added actions column
      ],
      sortBy: '',
      sortDesc: false,
      filter: null,
      pageOptions: [5, 10, 15, { value: 100, text: 'Show a lot' }],
      filterOn: [],
      currentPage: 1,
      perPage: 10,
      totalRows: 0
    }
  },
  computed: {
    // Computed property to filter and sort data based on user selections
    sortedAndFilteredData() {
      let data = [...this.data]

      if (this.filter) {
        const filter = this.filter.toLowerCase()
        data = data.filter((item) => {
          return Object.values(item).some((value) => {
            if (typeof value === 'string') {
              return value.toLowerCase().includes(filter)
            }
            return false
          })
        })
      }

      if (this.sortBy) {
        data = data.sort((a, b) => {
          const fieldA = a[this.sortBy]
          const fieldB = b[this.sortBy]
          if (this.sortDesc) {
            return fieldA > fieldB ? -1 : 1
          } else {
            return fieldA > fieldB ? 1 : -1
          }
        })
      }

      return data
    }
  },
  methods: {
    // Add your edit and delete item methods here
    editItem(item) {
      // Handle edit item action
      console.log('Edit item:', item)
      this.$router.push(`/item/${item.id}`)
    },
    confirmDelete(item) {
      // You can display a confirmation dialog here
      if (confirm(`Are you sure you want to delete ${item.platformName}?`)) {
        // Perform the delete action, for example, making an API request
        this.deleteItem(item)
      }
    },
    deleteItem(item) {
      // Implement the delete logic here, for example, making an API request
      // After successful deletion, you can update the view or take any other action
      console.log(`Deleted item with ID ${item.id}`)

      // If you want to refresh the data after deletion, you can call fetchData() again
      this.fetchData()
    },
    viewItem(item) {
      // Handle view item action
      console.log('View item:', item)
      this.$router.push(`/item/${item.id}`)
    },
    clearFilter() {
      this.filter = ''
    },
    onFiltered(filteredItems) {
      // Trigger pagination to update the number of buttons/pages due to filtering
      this.totalRows = filteredItems.length
      this.currentPage = 1
    },
    updateSort(sortBy) {
      if (this.sortBy === sortBy) {
        this.sortDesc = !this.sortDesc
      } else {
        this.sortBy = sortBy
        this.sortDesc = false
      }
    }
  },
  mounted() {
    // Fetch data from your API using Axios
    axios
      .get('http://localhost:3004/platforms')
      .then((response) => {
        this.data = response.data
        this.totalRows = this.data.length
      })
      .catch((error) => {
        console.error('Error fetching data:', error)
      })
  }
}
</script>

<style scoped>
/* Add Tailwind CSS classes for styling */
</style>
