// tailwind-platfrom-app-react/src/components/List.js
import React, { useState, useEffect } from "react";
import { Link, useLocation } from "react-router-dom";
import Pagination from "rc-pagination";
import "rc-pagination/assets/index.css";
import Axios from "axios";
import "./List.css";

const List = () => {
  const [data, setData] = useState([]);
  const [currentPage, setCurrentPage] = useState(1);
  const pageSize = 7;
  const [sortCriteria, setSortCriteria] = useState("platformName");

  const location = useLocation();

  useEffect(() => {
    const savedSortCriteria = localStorage.getItem("sortCriteria");
    if (savedSortCriteria) {
      setSortCriteria(savedSortCriteria);
    }
  }, []);

  const fetchData = async () => {
    try {
      const response = await Axios.get("http://localhost:3004/platforms");
      setData(response.data);
    } catch (error) {
      console.error("Error fetching data:", error);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  useEffect(() => {
    localStorage.setItem("sortCriteria", sortCriteria);
  }, [sortCriteria]);

  const startIndex = (currentPage - 1) * pageSize;
  const endIndex = startIndex + pageSize;

  const handleSort = (criteria) => {
    setSortCriteria(criteria);
  };

  const sortedData = [...data].sort((a, b) => {
    if (sortCriteria === "platformName") {
      return a.platformName.localeCompare(b.platformName);
    } else if (sortCriteria === "inventoryDate") {
      return new Date(a.inventoryDate) - new Date(b.inventoryDate);
    } else if (sortCriteria === "platformId") {
      return a.id - b.id;
    }
  });

  const [isOpen, setIsOpen] = useState(false);

  const toggleDropdown = () => {
    setIsOpen(!isOpen);
  };

  return (
    <div className="bg-gray-200 p-4 shadow-md rounded-lg">
      <h1 className="text-2xl font-bold mb-4">List of Platforms</h1>
      <div className="mb-4 flex items-center space-x-2">
        <label className="text-gray-700">Sort by:</label>
        <select
          value={sortCriteria}
          onChange={(e) => handleSort(e.target.value)}
          className="border border-gray-300 p-1 rounded-md"
        >
          <option value="platformName">Platform Name</option>
          <option value="inventoryDate">Date Created</option>
          <option value="platformId">ID</option>
        </select>
      </div>
      {sortedData.slice(startIndex, endIndex).map((item) => (
        <div
          key={item.id}
          className="bg-white shadow-md p-4 mb-4 rounded-lg transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-105 hover:bg-indigo-500 duration-300 ..."
        >
          <h2 className="text-xl font-semibold mb-2">
            Platform Name: {item.platformName}
          </h2>
          <p className="text-gray-600 mb-2">Platform ID: {item.id}</p>
          <p className="text-gray-600 mb-2">
            Inventory Date: {item.inventoryDate}
          </p>
          <div className="mb-4 flex items-center">
            <label className="text-gray-600 mr-2">Platform Type:</label>
            <div className="custom-dropdown">
              <span
                onClick={toggleDropdown}
                className="custom-dropdown-toggle cursor-pointer"
              >
                {item.platformType[0].name}
              </span>
              {isOpen && (
                <div className="custom-dropdown-content">
                  {item.platformType.map((type) => (
                    <div key={type.id} className="custom-dropdown-option">
                      {type.name}
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>

          <Link
            to={`/item/${item.id}`}
            state={{ from: location }} // Set the state.from to the current location
            className="text-blue-500 hover:underline"
          >
            View Details
          </Link>

        </div>
      ))}
      <Pagination
        pageSize={pageSize}
        current={currentPage}
        total={sortedData.length}
        onChange={setCurrentPage}
        className="mt-4"
      />
    </div>
  );
};

export default List;

// tailwind-platform-app-vue/src/components/List.vue
<template>
  <div class="bg-gray-200 p-4 shadow-md rounded-lg">
    <h1 class="text-2xl font-bold mb-4">List of Platforms</h1>
    <!-- Sorting options -->
    <div class="mb-4">
      <label for="sortBy" class="mr-2">Sort by:</label>
      <select v-model="sortBy" @change="updateSortCriteria">
        <option value="platformName">Platform Name</option>
        <option value="inventoryDate">Date Created</option>
        <option value="platformId">ID</option>
      </select>
    </div>

    <!-- Render paginated and sorted list here -->
    <div>
      <div
        v-for="item in sortedAndPaginatedData"
        :key="item.id"
        class="bg-white shadow-md p-4 mb-4 rounded-lg transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-105 hover:bg-indigo-500 duration-300 ..."
      >
        <h2 class="text-xl font-semibold mb-2">Platform Name: {{ item.platformName }}</h2>
        <p class="text-gray-600 mb-2">Platform ID: {{ item.id }}</p>
        <p class="text-gray-600 mb-2">Inventory Date: {{ item.inventoryDate }}</p>
        <div class="mb-4 flex items-center">
          <label class="text-gray-600 mr-2">Platform Type:</label>
          <div class="custom-dropdown">
            <span @click="toggleDropdown" class="custom-dropdown-toggle cursor-pointer">
              {{ selectedPlatformType }}
            </span>
            <div v-if="isOpen" class="custom-dropdown-content">
              <div
                v-for="type in item.platformType"
                :key="type.id"
                class="custom-dropdown-option"
                @click="selectedPlatformType(type.name)"
              >
                {{ type.name }}
              </div>
            </div>
          </div>
        </div>
        <router-link :to="'/item/' + item.id" class="text-blue-500 hover:underline">
          View Details
        </router-link>
      </div>
    </div>

    <!-- Pagination -->
    <pagination
      v-model="currentPage"
      :page-size="totalPages"
      :range-size="2"
      active-color="#DCEDFF"
      @update:modelValue="handlePageChange"
      class="mt-4"
    ></pagination>
  </div>
</template>

<script>
import axios from 'axios'
import { ref, computed, watch } from 'vue'
import Pagination from '@hennge/vue3-pagination'
import '@hennge/vue3-pagination/dist/vue3-pagination.css'

export default {
  components: {
    pagination: Pagination
  },

  setup() {
    const data = ref([])
    const currentPage = ref(1)
    const pageSize = 7
    const sortBy = ref('platformName') // Set the initial sorting criteria
    const selectedPlatformType = ref('') // Initialize selectedPlatformType

    const fetchData = async () => {
      try {
        const response = await axios.get('http://localhost:3004/platforms')
        data.value = response.data
      } catch (error) {
        console.error('Error fetching data:', error)
      }
    }

    const sortedAndPaginatedData = computed(() => {
      let sortedData = [...data.value]

      if (sortBy.value === 'platformName') {
        sortedData.sort((a, b) => a.platformName.localeCompare(b.platformName))
      } else if (sortBy.value === 'inventoryDate') {
        sortedData.sort((a, b) => new Date(a.inventoryDate) - new Date(b.inventoryDate))
      } else if (sortBy.value === 'platformId') {
        sortedData.sort((a, b) => a.id - b.id)
      }

      const startIndex = (currentPage.value - 1) * pageSize
      return sortedData.slice(startIndex, startIndex + pageSize)
    })

    const totalPages = computed(() => {
      return Math.ceil(data.value.length / pageSize)
    })

    const updateSortCriteria = () => {
      // Update sorting criteria when changed
      fetchData() // Fetch data again after changing the sorting criteria
    }

    const handlePageChange = (newPage) => {
      currentPage.value = newPage
    }

    fetchData() // Fetch data on component creation

    watch(sortBy, () => {
      currentPage.value = 1 // Reset to the first page when changing sorting criteria
    })

    const isOpen = ref(false) // Initialize isOpen as a ref

    const toggleDropdown = () => {
      isOpen.value = !isOpen.value
    }

    const selectPlatformType = (type) => {
      selectedPlatformType.value = type // Update the selected platform type
      isOpen.value = false // Close the dropdown
    }

    return {
      data,
      currentPage,
      pageSize,
      sortBy,
      sortedAndPaginatedData,
      totalPages,
      updateSortCriteria,
      handlePageChange,
      toggleDropdown,
      isOpen,
      selectedPlatformType
    }
  }
}
</script>

<style scoped>
/* Your custom styles here */
</style>
