// tailwind-platfrom-app-react/src/App.js
import React from "react";
import { Route, Routes } from "react-router-dom";
import List from "./components/List";
import ItemDetail from "./components/ItemDetail";
import WrongRoute from "./components/WrongRoute";
import EditItem from "./components/EditItem";
import DataGrid from "./components/DataGrid";
import LandingPage from "./components/LandingPage";

function App() {
  return (
    <div className="container mx-auto p-4">
      <Routes>
        {/* Route for the list page */}
        <Route path="/list" element={<List />}></Route>
        {/* <Route path="/item:id" element={<ItemDetail />}></Route>  */}
        <Route path="/item/:id" element={<ItemDetail />}></Route>
        <Route path="/item/:id/edit" element={<EditItem />}></Route>
        <Route path="/datagrid" element={<DataGrid />}></Route>
        <Route path="/" element={<LandingPage />}></Route>
        <Route path="*" element={<WrongRoute />}></Route>
      </Routes>
    </div>
  );
}

export default App;

// tailwind-platform-app-solid-js/src/App.jsx
import { createSignal } from 'solid-js';
import { Routes, Route, A } from "@solidjs/router";

import banner from './assets/banner.png';
import Home from './pages/Home';


import { useCartContext } from "./context/CartContext";
import DataGrid from './pages/DataGrid';
import EditItem from './pages/EditItem';
import ItemDetail from './pages/ItemDetail';
import List from './pages/List';
import ListItem from './pages/ListItem';
import WrongRoute from './pages/WrongRoute';
import LandingPage from './pages/LandingPage';


function App() {
  const [darkTheme, setDarkTheme] = createSignal(false)

  

  const { items } = useCartContext()

  const quantity = () => {
    return items.reduce((acc, current) => {
      return acc + current.quantity
    }, 0)
  }

  return (
    <div class="container m-auto bg">
      <header
        class="my-4 p-2 text-xl flex items-center gap-4 justify-end"
      >


      </header>
      
      

      <Routes>
      <Route path="/" component={LandingPage} />
        <Route path="/DataGrid" component={DataGrid} />
        <Route path="/item/:id/edit" component={EditItem} />
        <Route path="/item/:id" component={ItemDetail} />
        <Route path="/List" component={List} />
        <Route path="*" component={WrongRoute} />
        
        
      </Routes>
      
    </div>
  );
}

export default App;
